/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IProntera } from "./IProntera";
export * as factories from "./factories";
export { IProntera__factory } from "./factories/IProntera__factory";
